### ISSUE TITLE
List items won't go in a row

### ISSUE THREAD

**Issue by naomileron** [imd1005-web-development-winter-2023/assignment-02-naomileron#2]
@neilmispelaar 

In one of my sections, I'm trying to get my li tags in css to go in a row, but they will only stay in a column. How do I fix this?

**Comment by neilmispelaar** [comment]
Make sure that the parent ul is `display:flex`

Could you share which section of your page you want to make the `ul` display in a row?

**Comment by naomileron** [comment]
I realized that it was because I had a tag that wasn't supposed to be there. It's working now. Sorry about that.

**Comment by neilmispelaar** [comment]
No worries! 

Thanks for reaching out. Glad that you were able to sort it out! Well done!
