### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by naomileron** [imd1005-web-development-winter-2023/assignment-02-naomileron#4]
@neilmispelaar 
I just handed in the assignment, but I just wanted to let you know that my cite looks best in google chrome. The reset.css is linked in my html, but when I tested my cite in different browsers, some things were off.
Thank you for all the help!

**Comment by neilmispelaar** [comment]
Congratulations! 🎉🚀

I’ll definitely test in a chromium based browser  and have a look at your code to see if anything stands out.

**Comment by naomileron** [comment]
Thank you!
